CREATE SEQUENCE IF NOT EXISTS account_sequence START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS audit_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE account
(
    id             BIGINT       NOT NULL,
    balance        DECIMAL,
    account_number VARCHAR(255),
    currency       VARCHAR(255),
    account_types  VARCHAR(255),
    status         VARCHAR(255) NOT NULL,
    closed_at      TIMESTAMP WITHOUT TIME ZONE,
    version        BIGINT,
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    user_id        VARCHAR(255),
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE audit_logs
(
    id             BIGINT  NOT NULL,
    actor_id       VARCHAR(255),
    target_id      VARCHAR(255),
    action         VARCHAR(255),
    success        BOOLEAN NOT NULL,
    failure_reason VARCHAR(255),
    reason         VARCHAR(255),
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE beneficiary
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    account_number VARCHAR(255),
    user_id        VARCHAR(255),
    CONSTRAINT pk_beneficiary PRIMARY KEY (id)
);

CREATE TABLE idempotency_key
(
    key            VARCHAR(255) NOT NULL,
    transaction_id VARCHAR(255),
    status         VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    request_hash   VARCHAR(255),
    CONSTRAINT pk_idempotencykey PRIMARY KEY (key)
);

CREATE TABLE transactions
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id        VARCHAR(255),
    amount                DECIMAL,
    transaction_type      VARCHAR(255),
    transaction_reference VARCHAR(255),
    created_date          date,
    status                VARCHAR(255),
    reverse_of            VARCHAR(255),
    narration             VARCHAR(255),
    sender_account_id     BIGINT,
    recepient_account_id  BIGINT,
    receipt_pdf           OID,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

CREATE TABLE user_security
(
    id                  VARCHAR(255) NOT NULL,
    transaction_pin     VARCHAR(255) NOT NULL,
    pin_failed_attempts INTEGER      NOT NULL,
    pin_locked_until    TIMESTAMP WITHOUT TIME ZONE,
    user_id             VARCHAR(255),
    CONSTRAINT pk_user_security PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            VARCHAR(255) NOT NULL,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    username      VARCHAR(255),
    email         VARCHAR(255),
    address       VARCHAR(255),
    city          VARCHAR(255),
    country       VARCHAR(255),
    phone         VARCHAR(255),
    status        VARCHAR(255) NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE account
    ADD CONSTRAINT uc_account_accountnumber UNIQUE (account_number);

ALTER TABLE beneficiary
    ADD CONSTRAINT uc_beneficiary_name UNIQUE (name);

ALTER TABLE user_security
    ADD CONSTRAINT uc_user_security_transactionpin UNIQUE (transaction_pin);

ALTER TABLE user_security
    ADD CONSTRAINT uc_user_security_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX "idx_users_email on" ON users (email);

ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE beneficiary
    ADD CONSTRAINT FK_BENEFICIARY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_RECEPIENT_ACCOUNT FOREIGN KEY (recepient_account_id) REFERENCES account (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_SENDER_ACCOUNT FOREIGN KEY (sender_account_id) REFERENCES account (id);

ALTER TABLE user_security
    ADD CONSTRAINT FK_USER_SECURITY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);